// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calorie_estimations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCalorieEstimation = `-- name: CreateCalorieEstimation :one
INSERT INTO calorie_estimations (id, user_id, description, estimated_calories, confidence, items, observation)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, description, estimated_calories, confidence, items, observation, created_at
`

type CreateCalorieEstimationParams struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	Description       string
	EstimatedCalories int32
	Confidence        string
	Items             []byte
	Observation       pgtype.Text
}

func (q *Queries) CreateCalorieEstimation(ctx context.Context, arg CreateCalorieEstimationParams) (CalorieEstimation, error) {
	row := q.db.QueryRow(ctx, createCalorieEstimation,
		arg.ID,
		arg.UserID,
		arg.Description,
		arg.EstimatedCalories,
		arg.Confidence,
		arg.Items,
		arg.Observation,
	)
	var i CalorieEstimation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.EstimatedCalories,
		&i.Confidence,
		&i.Items,
		&i.Observation,
		&i.CreatedAt,
	)
	return i, err
}

const listCalorieEstimationsByUser = `-- name: ListCalorieEstimationsByUser :many
SELECT id, user_id, description, estimated_calories, confidence, items, observation, created_at FROM calorie_estimations
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 20
`

func (q *Queries) ListCalorieEstimationsByUser(ctx context.Context, userID pgtype.UUID) ([]CalorieEstimation, error) {
	rows, err := q.db.Query(ctx, listCalorieEstimationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CalorieEstimation
	for rows.Next() {
		var i CalorieEstimation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Description,
			&i.EstimatedCalories,
			&i.Confidence,
			&i.Items,
			&i.Observation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
