// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: food_plans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFoodPlan = `-- name: CreateFoodPlan :one
INSERT INTO food_plans (id, user_id, title, description, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, title, description, is_active, created_at, updated_at
`

type CreateFoodPlanParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Title       string
	Description pgtype.Text
	IsActive    bool
}

func (q *Queries) CreateFoodPlan(ctx context.Context, arg CreateFoodPlanParams) (FoodPlan, error) {
	row := q.db.QueryRow(ctx, createFoodPlan,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.IsActive,
	)
	var i FoodPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateAllUserFoodPlans = `-- name: DeactivateAllUserFoodPlans :exec
UPDATE food_plans
SET is_active = false, updated_at = now()
WHERE user_id = $1
`

func (q *Queries) DeactivateAllUserFoodPlans(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateAllUserFoodPlans, userID)
	return err
}

const deleteFoodPlan = `-- name: DeleteFoodPlan :exec
DELETE FROM food_plans
WHERE id = $1 AND user_id = $2
`

type DeleteFoodPlanParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteFoodPlan(ctx context.Context, arg DeleteFoodPlanParams) error {
	_, err := q.db.Exec(ctx, deleteFoodPlan, arg.ID, arg.UserID)
	return err
}

const getActiveFoodPlan = `-- name: GetActiveFoodPlan :one
SELECT id, user_id, title, description, is_active, created_at, updated_at FROM food_plans
WHERE user_id = $1 AND is_active = true
LIMIT 1
`

func (q *Queries) GetActiveFoodPlan(ctx context.Context, userID pgtype.UUID) (FoodPlan, error) {
	row := q.db.QueryRow(ctx, getActiveFoodPlan, userID)
	var i FoodPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFoodPlanByIDAndUserID = `-- name: GetFoodPlanByIDAndUserID :one
SELECT id, user_id, title, description, is_active, created_at, updated_at FROM food_plans
WHERE id = $1 AND user_id = $2
`

type GetFoodPlanByIDAndUserIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetFoodPlanByIDAndUserID(ctx context.Context, arg GetFoodPlanByIDAndUserIDParams) (FoodPlan, error) {
	row := q.db.QueryRow(ctx, getFoodPlanByIDAndUserID, arg.ID, arg.UserID)
	var i FoodPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFoodPlansByUser = `-- name: ListFoodPlansByUser :many
SELECT id, user_id, title, description, is_active, created_at, updated_at FROM food_plans
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFoodPlansByUser(ctx context.Context, userID pgtype.UUID) ([]FoodPlan, error) {
	rows, err := q.db.Query(ctx, listFoodPlansByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FoodPlan
	for rows.Next() {
		var i FoodPlan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFoodPlanActive = `-- name: SetFoodPlanActive :one
UPDATE food_plans
SET is_active = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, title, description, is_active, created_at, updated_at
`

type SetFoodPlanActiveParams struct {
	ID       pgtype.UUID
	IsActive bool
}

func (q *Queries) SetFoodPlanActive(ctx context.Context, arg SetFoodPlanActiveParams) (FoodPlan, error) {
	row := q.db.QueryRow(ctx, setFoodPlanActive, arg.ID, arg.IsActive)
	var i FoodPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFoodPlan = `-- name: UpdateFoodPlan :one
UPDATE food_plans
SET title = $3, description = $4, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, description, is_active, created_at, updated_at
`

type UpdateFoodPlanParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Title       string
	Description pgtype.Text
}

func (q *Queries) UpdateFoodPlan(ctx context.Context, arg UpdateFoodPlanParams) (FoodPlan, error) {
	row := q.db.QueryRow(ctx, updateFoodPlan,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
	)
	var i FoodPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
