// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: food_plan_meals.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFoodPlanMeal = `-- name: CreateFoodPlanMeal :one
INSERT INTO food_plan_meals (id, food_plan_day_id, name, description, scheduled_time, calories, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, food_plan_day_id, name, description, scheduled_time, calories, sort_order, created_at, updated_at
`

type CreateFoodPlanMealParams struct {
	ID            pgtype.UUID
	FoodPlanDayID pgtype.UUID
	Name          string
	Description   pgtype.Text
	ScheduledTime pgtype.Text
	Calories      pgtype.Int4
	SortOrder     int32
}

func (q *Queries) CreateFoodPlanMeal(ctx context.Context, arg CreateFoodPlanMealParams) (FoodPlanMeal, error) {
	row := q.db.QueryRow(ctx, createFoodPlanMeal,
		arg.ID,
		arg.FoodPlanDayID,
		arg.Name,
		arg.Description,
		arg.ScheduledTime,
		arg.Calories,
		arg.SortOrder,
	)
	var i FoodPlanMeal
	err := row.Scan(
		&i.ID,
		&i.FoodPlanDayID,
		&i.Name,
		&i.Description,
		&i.ScheduledTime,
		&i.Calories,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFoodPlanMeal = `-- name: DeleteFoodPlanMeal :exec
DELETE FROM food_plan_meals
WHERE id = $1
`

func (q *Queries) DeleteFoodPlanMeal(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFoodPlanMeal, id)
	return err
}

const getFoodPlanMealByID = `-- name: GetFoodPlanMealByID :one
SELECT id, food_plan_day_id, name, description, scheduled_time, calories, sort_order, created_at, updated_at FROM food_plan_meals
WHERE id = $1
`

func (q *Queries) GetFoodPlanMealByID(ctx context.Context, id pgtype.UUID) (FoodPlanMeal, error) {
	row := q.db.QueryRow(ctx, getFoodPlanMealByID, id)
	var i FoodPlanMeal
	err := row.Scan(
		&i.ID,
		&i.FoodPlanDayID,
		&i.Name,
		&i.Description,
		&i.ScheduledTime,
		&i.Calories,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFoodPlanMealsByDay = `-- name: ListFoodPlanMealsByDay :many
SELECT id, food_plan_day_id, name, description, scheduled_time, calories, sort_order, created_at, updated_at FROM food_plan_meals
WHERE food_plan_day_id = $1
ORDER BY sort_order, scheduled_time
`

func (q *Queries) ListFoodPlanMealsByDay(ctx context.Context, foodPlanDayID pgtype.UUID) ([]FoodPlanMeal, error) {
	rows, err := q.db.Query(ctx, listFoodPlanMealsByDay, foodPlanDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FoodPlanMeal
	for rows.Next() {
		var i FoodPlanMeal
		if err := rows.Scan(
			&i.ID,
			&i.FoodPlanDayID,
			&i.Name,
			&i.Description,
			&i.ScheduledTime,
			&i.Calories,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFoodPlanMeal = `-- name: UpdateFoodPlanMeal :one
UPDATE food_plan_meals
SET name           = $2,
    description    = $3,
    scheduled_time = $4,
    calories       = $5,
    sort_order     = $6,
    updated_at     = now()
WHERE id = $1
RETURNING id, food_plan_day_id, name, description, scheduled_time, calories, sort_order, created_at, updated_at
`

type UpdateFoodPlanMealParams struct {
	ID            pgtype.UUID
	Name          string
	Description   pgtype.Text
	ScheduledTime pgtype.Text
	Calories      pgtype.Int4
	SortOrder     int32
}

func (q *Queries) UpdateFoodPlanMeal(ctx context.Context, arg UpdateFoodPlanMealParams) (FoodPlanMeal, error) {
	row := q.db.QueryRow(ctx, updateFoodPlanMeal,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ScheduledTime,
		arg.Calories,
		arg.SortOrder,
	)
	var i FoodPlanMeal
	err := row.Scan(
		&i.ID,
		&i.FoodPlanDayID,
		&i.Name,
		&i.Description,
		&i.ScheduledTime,
		&i.Calories,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
