// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: food_plan_days.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFoodPlanDay = `-- name: CreateFoodPlanDay :one
INSERT INTO food_plan_days (id, food_plan_id, weekday)
VALUES ($1, $2, $3)
RETURNING id, food_plan_id, weekday, created_at, updated_at
`

type CreateFoodPlanDayParams struct {
	ID         pgtype.UUID
	FoodPlanID pgtype.UUID
	Weekday    int16
}

func (q *Queries) CreateFoodPlanDay(ctx context.Context, arg CreateFoodPlanDayParams) (FoodPlanDay, error) {
	row := q.db.QueryRow(ctx, createFoodPlanDay, arg.ID, arg.FoodPlanID, arg.Weekday)
	var i FoodPlanDay
	err := row.Scan(
		&i.ID,
		&i.FoodPlanID,
		&i.Weekday,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFoodPlanDayByWeekday = `-- name: GetFoodPlanDayByWeekday :one
SELECT id, food_plan_id, weekday, created_at, updated_at FROM food_plan_days
WHERE food_plan_id = $1 AND weekday = $2
`

type GetFoodPlanDayByWeekdayParams struct {
	FoodPlanID pgtype.UUID
	Weekday    int16
}

func (q *Queries) GetFoodPlanDayByWeekday(ctx context.Context, arg GetFoodPlanDayByWeekdayParams) (FoodPlanDay, error) {
	row := q.db.QueryRow(ctx, getFoodPlanDayByWeekday, arg.FoodPlanID, arg.Weekday)
	var i FoodPlanDay
	err := row.Scan(
		&i.ID,
		&i.FoodPlanID,
		&i.Weekday,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFoodPlanDays = `-- name: ListFoodPlanDays :many
SELECT id, food_plan_id, weekday, created_at, updated_at FROM food_plan_days
WHERE food_plan_id = $1
ORDER BY weekday
`

func (q *Queries) ListFoodPlanDays(ctx context.Context, foodPlanID pgtype.UUID) ([]FoodPlanDay, error) {
	rows, err := q.db.Query(ctx, listFoodPlanDays, foodPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FoodPlanDay
	for rows.Next() {
		var i FoodPlanDay
		if err := rows.Scan(
			&i.ID,
			&i.FoodPlanID,
			&i.Weekday,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
