// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meals.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (
    id,
    user_id,
    name,
    description,
    eaten_at,
    is_on_diet,
    calories
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, food_plan_meal_id, food_plan_meal_snapshot, name, description, eaten_at, is_on_diet, calories, created_at, updated_at
`

type CreateMealParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Name        string
	Description pgtype.Text
	EatenAt     pgtype.Timestamp
	IsOnDiet    bool
	Calories    pgtype.Int4
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error) {
	row := q.db.QueryRow(ctx, createMeal,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.EatenAt,
		arg.IsOnDiet,
		arg.Calories,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FoodPlanMealID,
		&i.FoodPlanMealSnapshot,
		&i.Name,
		&i.Description,
		&i.EatenAt,
		&i.IsOnDiet,
		&i.Calories,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMeal = `-- name: DeleteMeal :exec
DELETE FROM meals
WHERE id = $1 AND user_id = $2
`

type DeleteMealParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteMeal(ctx context.Context, arg DeleteMealParams) error {
	_, err := q.db.Exec(ctx, deleteMeal, arg.ID, arg.UserID)
	return err
}

const getMealByIDAndUserID = `-- name: GetMealByIDAndUserID :one
SELECT id, user_id, food_plan_meal_id, food_plan_meal_snapshot, name, description, eaten_at, is_on_diet, calories, created_at, updated_at FROM meals
WHERE id = $1 AND user_id = $2
`

type GetMealByIDAndUserIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetMealByIDAndUserID(ctx context.Context, arg GetMealByIDAndUserIDParams) (Meal, error) {
	row := q.db.QueryRow(ctx, getMealByIDAndUserID, arg.ID, arg.UserID)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FoodPlanMealID,
		&i.FoodPlanMealSnapshot,
		&i.Name,
		&i.Description,
		&i.EatenAt,
		&i.IsOnDiet,
		&i.Calories,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMealsByUserFiltered = `-- name: ListMealsByUserFiltered :many
SELECT id, user_id, food_plan_meal_id, food_plan_meal_snapshot, name, description, eaten_at, is_on_diet, calories, created_at, updated_at FROM meals
WHERE user_id = $1
  AND ($2::TIMESTAMP IS NULL OR eaten_at >= $2)
  AND ($3::TIMESTAMP IS NULL OR eaten_at <= $3)
  AND ($4::BOOLEAN IS NULL OR is_on_diet = $4)
ORDER BY eaten_at DESC
`

type ListMealsByUserFilteredParams struct {
	UserID    pgtype.UUID
	StartDate pgtype.Timestamp
	EndDate   pgtype.Timestamp
	IsOnDiet  pgtype.Bool
}

func (q *Queries) ListMealsByUserFiltered(ctx context.Context, arg ListMealsByUserFilteredParams) ([]Meal, error) {
	rows, err := q.db.Query(ctx, listMealsByUserFiltered,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.IsOnDiet,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FoodPlanMealID,
			&i.FoodPlanMealSnapshot,
			&i.Name,
			&i.Description,
			&i.EatenAt,
			&i.IsOnDiet,
			&i.Calories,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMeal = `-- name: UpdateMeal :one
UPDATE meals
SET
    name        = $3,
    description = $4,
    eaten_at    = $5,
    is_on_diet  = $6,
    calories    = $7,
    updated_at  = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, food_plan_meal_id, food_plan_meal_snapshot, name, description, eaten_at, is_on_diet, calories, created_at, updated_at
`

type UpdateMealParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Name        string
	Description pgtype.Text
	EatenAt     pgtype.Timestamp
	IsOnDiet    bool
	Calories    pgtype.Int4
}

func (q *Queries) UpdateMeal(ctx context.Context, arg UpdateMealParams) (Meal, error) {
	row := q.db.QueryRow(ctx, updateMeal,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.EatenAt,
		arg.IsOnDiet,
		arg.Calories,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FoodPlanMealID,
		&i.FoodPlanMealSnapshot,
		&i.Name,
		&i.Description,
		&i.EatenAt,
		&i.IsOnDiet,
		&i.Calories,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
