// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMetricsSummary = `-- name: GetMetricsSummary :one
SELECT
    COUNT(*)                              AS total_meals,
    COUNT(*) FILTER (WHERE is_on_diet)    AS total_on_diet,
    COUNT(*) FILTER (WHERE NOT is_on_diet) AS total_off_diet
FROM meals
WHERE user_id = $1
`

type GetMetricsSummaryRow struct {
	TotalMeals   int64
	TotalOnDiet  int64
	TotalOffDiet int64
}

func (q *Queries) GetMetricsSummary(ctx context.Context, userID pgtype.UUID) (GetMetricsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getMetricsSummary, userID)
	var i GetMetricsSummaryRow
	err := row.Scan(&i.TotalMeals, &i.TotalOnDiet, &i.TotalOffDiet)
	return i, err
}

const listMealsGroupedByDay = `-- name: ListMealsGroupedByDay :many
SELECT
    DATE(eaten_at)                                  AS date,
    COUNT(*)                                        AS total_meals,
    COUNT(*) FILTER (WHERE is_on_diet)              AS total_on_diet,
    COUNT(*) FILTER (WHERE NOT is_on_diet)          AS total_off_diet,
    COALESCE(SUM(calories), 0)::BIGINT              AS total_calories
FROM meals
WHERE user_id = $1
  AND eaten_at >= $2
  AND eaten_at <= $3
GROUP BY DATE(eaten_at)
ORDER BY date
`

type ListMealsGroupedByDayParams struct {
	UserID    pgtype.UUID
	EatenAt   pgtype.Timestamp
	EatenAt_2 pgtype.Timestamp
}

type ListMealsGroupedByDayRow struct {
	Date          pgtype.Date
	TotalMeals    int64
	TotalOnDiet   int64
	TotalOffDiet  int64
	TotalCalories int64
}

func (q *Queries) ListMealsGroupedByDay(ctx context.Context, arg ListMealsGroupedByDayParams) ([]ListMealsGroupedByDayRow, error) {
	rows, err := q.db.Query(ctx, listMealsGroupedByDay, arg.UserID, arg.EatenAt, arg.EatenAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMealsGroupedByDayRow
	for rows.Next() {
		var i ListMealsGroupedByDayRow
		if err := rows.Scan(
			&i.Date,
			&i.TotalMeals,
			&i.TotalOnDiet,
			&i.TotalOffDiet,
			&i.TotalCalories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealsGroupedByMonth = `-- name: ListMealsGroupedByMonth :many
SELECT
    DATE_TRUNC('month', eaten_at)::DATE             AS date,
    COUNT(*)                                        AS total_meals,
    COUNT(*) FILTER (WHERE is_on_diet)              AS total_on_diet,
    COUNT(*) FILTER (WHERE NOT is_on_diet)          AS total_off_diet,
    COALESCE(SUM(calories), 0)::BIGINT              AS total_calories
FROM meals
WHERE user_id = $1
  AND eaten_at >= $2
  AND eaten_at <= $3
GROUP BY DATE_TRUNC('month', eaten_at)
ORDER BY date
`

type ListMealsGroupedByMonthParams struct {
	UserID    pgtype.UUID
	EatenAt   pgtype.Timestamp
	EatenAt_2 pgtype.Timestamp
}

type ListMealsGroupedByMonthRow struct {
	Date          pgtype.Date
	TotalMeals    int64
	TotalOnDiet   int64
	TotalOffDiet  int64
	TotalCalories int64
}

func (q *Queries) ListMealsGroupedByMonth(ctx context.Context, arg ListMealsGroupedByMonthParams) ([]ListMealsGroupedByMonthRow, error) {
	rows, err := q.db.Query(ctx, listMealsGroupedByMonth, arg.UserID, arg.EatenAt, arg.EatenAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMealsGroupedByMonthRow
	for rows.Next() {
		var i ListMealsGroupedByMonthRow
		if err := rows.Scan(
			&i.Date,
			&i.TotalMeals,
			&i.TotalOnDiet,
			&i.TotalOffDiet,
			&i.TotalCalories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealsOnDietStatus = `-- name: ListMealsOnDietStatus :many
SELECT is_on_diet FROM meals
WHERE user_id = $1
  AND ($2::TIMESTAMP IS NULL OR eaten_at >= $2)
  AND ($3::TIMESTAMP IS NULL OR eaten_at <= $3)
ORDER BY eaten_at ASC
`

type ListMealsOnDietStatusParams struct {
	UserID    pgtype.UUID
	StartDate pgtype.Timestamp
	EndDate   pgtype.Timestamp
}

func (q *Queries) ListMealsOnDietStatus(ctx context.Context, arg ListMealsOnDietStatusParams) ([]bool, error) {
	rows, err := q.db.Query(ctx, listMealsOnDietStatus, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []bool
	for rows.Next() {
		var is_on_diet bool
		if err := rows.Scan(&is_on_diet); err != nil {
			return nil, err
		}
		items = append(items, is_on_diet)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
