// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Meal struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	FoodPlanMealID       pgtype.UUID
	FoodPlanMealSnapshot []byte
	Name                 string
	Description          pgtype.Text
	EatenAt              pgtype.Timestamp
	IsOnDiet             bool
	Calories             pgtype.Int4
	CreatedAt            pgtype.Timestamp
	UpdatedAt            pgtype.Timestamp
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID           pgtype.UUID
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
