// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_profiles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserProfile = `-- name: GetUserProfile :one
SELECT id, user_id, weight_kg, height_cm, birth_date, body_fat_percentage, basal_calories, activity_level, gym_frequency_per_week, created_at, updated_at FROM user_profiles
WHERE user_id = $1
`

func (q *Queries) GetUserProfile(ctx context.Context, userID pgtype.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfile, userID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeightKg,
		&i.HeightCm,
		&i.BirthDate,
		&i.BodyFatPercentage,
		&i.BasalCalories,
		&i.ActivityLevel,
		&i.GymFrequencyPerWeek,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserProfile = `-- name: UpsertUserProfile :one
INSERT INTO user_profiles (id, user_id, weight_kg, height_cm, birth_date, body_fat_percentage, basal_calories, activity_level, gym_frequency_per_week)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id) DO UPDATE
SET weight_kg              = EXCLUDED.weight_kg,
    height_cm              = EXCLUDED.height_cm,
    birth_date             = EXCLUDED.birth_date,
    body_fat_percentage    = EXCLUDED.body_fat_percentage,
    basal_calories         = EXCLUDED.basal_calories,
    activity_level         = EXCLUDED.activity_level,
    gym_frequency_per_week = EXCLUDED.gym_frequency_per_week,
    updated_at             = now()
RETURNING id, user_id, weight_kg, height_cm, birth_date, body_fat_percentage, basal_calories, activity_level, gym_frequency_per_week, created_at, updated_at
`

type UpsertUserProfileParams struct {
	ID                  pgtype.UUID
	UserID              pgtype.UUID
	WeightKg            pgtype.Numeric
	HeightCm            pgtype.Int4
	BirthDate           pgtype.Date
	BodyFatPercentage   pgtype.Numeric
	BasalCalories       pgtype.Int4
	ActivityLevel       pgtype.Text
	GymFrequencyPerWeek pgtype.Int4
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, upsertUserProfile,
		arg.ID,
		arg.UserID,
		arg.WeightKg,
		arg.HeightCm,
		arg.BirthDate,
		arg.BodyFatPercentage,
		arg.BasalCalories,
		arg.ActivityLevel,
		arg.GymFrequencyPerWeek,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeightKg,
		&i.HeightCm,
		&i.BirthDate,
		&i.BodyFatPercentage,
		&i.BasalCalories,
		&i.ActivityLevel,
		&i.GymFrequencyPerWeek,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
